server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: springboot-init
  # ?? dev ??
  profiles:
    active: dev

  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_dba
    username: root
    password: root

  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
